using System;
using System.Collections.Generic;
using Il2Cpp;

namespace BallXPitArchipelago;

/// <summary>
/// "Evosanity": a location check for every unique ball discovered, and optionally a win
/// condition built on them. See the ballxpit apworld's Options.py (Evosanity/Goal) and Balls.py.
///
/// Detection is pure field-read polling of MetaSaveData.I.HeroStats - deliberately NOT a Harmony
/// patch on anything in the merge path (UpgradeMgr.CombineHeroes, HeroInst.CombineWith,
/// LevelUpUI, ...). There's no need: the stats array is reachable directly from the singleton,
/// and this project has already paid the price once for patching a leaf method that vanilla calls
/// reentrant from deep inside native code (see DebugHooks.cs's removal note and EconomyHooks.cs -
/// patching SaveMgr.SpendResources froze the game unconditionally). Polling has none of that
/// risk and slots into the PollForChanges() tick LocationHooks already runs.
///
/// Confirmed live (2026-09-13 dump) that HeroStats is length HeroType.kNum, indexed by HeroType
/// ordinal, and that NumObtained flips 0 -> 1 the MOMENT a ball is obtained mid-run rather than
/// being batched to run end - Virus and Spider Queen both transitioned at CurState=kPlaying. So
/// checks fire immediately, which is what the option's description promises players.
/// </summary>
internal static class EvosanityOptions
{
    internal enum Scope
    {
        /// <summary>No ball checks at all - the locations aren't in this slot's data package.</summary>
        None,

        /// <summary>The 69 evolved (merged) balls.</summary>
        Evolutions,

        /// <summary>The 69 evolved balls plus the 21 base balls - every encyclopedia ball entry.</summary>
        AllBalls,
    }

    internal static Scope BallScope { get; private set; } = Scope.None;

    /// <summary>
    /// True when the yaml asked for goal=evosanity: every evolved ball must be discovered AND all
    /// 8 biomes beaten. A deliberate superset of the all_biomes goal rather than an alternative to
    /// it - no ball is unlocked by beating the 8th biome (Vast Void unlocks nothing at all,
    /// confirmed live), so "evolve everything" alone would leave the hardest biome skippable.
    /// </summary>
    internal static bool GoalIsEvosanity { get; private set; }

    internal static void ApplyFromSlotData(Dictionary<string, object> slotData)
    {
        if (slotData == null)
            return;

        BallScope = ReadScope(slotData);
        GoalIsEvosanity = ReadString(slotData, "goal") == "evosanity";

        var goalName = GoalIsEvosanity ? "evosanity" : "all_biomes";
        LocationHooks.Log?.Msg($"[Evosanity] scope={BallScope}, goal={goalName}");
    }

    private static Scope ReadScope(Dictionary<string, object> slotData) => ReadString(slotData, "evosanity") switch
    {
        "evolutions" => Scope.Evolutions,
        "all_balls" => Scope.AllBalls,
        // Includes "none" and the missing/unparseable case: a seed generated by an older apworld
        // has no "evosanity" key at all, and defaulting to off is both correct for it and the only
        // safe guess - reporting checks for locations that don't exist in the data package would
        // just spam warnings.
        _ => Scope.None,
    };

    private static string ReadString(Dictionary<string, object> slotData, string key)
    {
        if (!slotData.TryGetValue(key, out var value) || value == null)
            return null;

        try { return Convert.ToString(value); }
        catch { return null; }
    }

    /// <summary>Whether this ball has a location in the current slot, per the evosanity scope.</summary>
    internal static bool IsTracked(HeroType ball) => BallScope switch
    {
        Scope.Evolutions => GameNames.EvolvedBalls.Contains(ball),
        Scope.AllBalls => GameNames.EvolvedBalls.Contains(ball) || GameNames.BaseBalls.Contains(ball),
        _ => false,
    };

    /// <summary>
    /// The apworld's location name for a ball (Locations.py). Two conventions rather than one,
    /// because the two halves are different actions: an evolved ball is something you construct
    /// out of level-3 components, a base ball is something you're simply offered and take.
    /// </summary>
    internal static string LocationNameFor(HeroType ball) =>
        GameNames.EvolvedBalls.Contains(ball)
            ? "Evolve: " + GameNames.BallDisplay(ball)
            : "Discover Ball: " + GameNames.BallDisplay(ball);
}

/// <summary>
/// Polls MetaSaveData.I.HeroStats for newly-discovered balls and reports them as location checks.
/// Driven from LocationHooks.PollForChanges().
/// </summary>
internal static class BallDiscoveryTracker
{
    /// <summary>
    /// Which ball indices we've already reported this process. Purely to keep the log readable -
    /// LocationHooks.SendCheck already refuses to re-send an already-checked location, but it logs
    /// a line each time it does, which at a few polls per second over 90 balls would bury
    /// everything else.
    /// </summary>
    private static bool[] _reported;

    /// <summary>
    /// Unlike the level-completion poll in LocationHooks (which suppresses its first pass, since
    /// loading a save isn't a fresh completion), this reports everything already discovered the
    /// first time it runs. That's deliberate: a discovered ball is permanent meta-progress that
    /// the location genuinely represents, so if you have already made Frozen Flame, that check is
    /// earned. On the fresh save an evosanity seed expects it's a no-op; on an existing save it
    /// front-loads a burst of checks, which is the honest reading rather than a surprise.
    /// </summary>
    internal static void Poll()
    {
        if (EvosanityOptions.BallScope == EvosanityOptions.Scope.None)
            return;

        var stats = MetaSaveData.I?.HeroStats;
        if (stats == null)
            return;

        if (_reported == null || _reported.Length != stats.Length)
            _reported = new bool[stats.Length];

        for (var i = 0; i < stats.Length; i++)
        {
            if (_reported[i])
                continue;

            var s = stats[i];
            if (s == null || s.NumObtained <= 0)
                continue;

            _reported[i] = true;

            // HeroStats is indexed by HeroType ordinal (confirmed live). Guard anyway: if a game
            // update ever grew the enum, an out-of-range index would otherwise produce a nonsense
            // location name instead of an obvious warning.
            if (i >= (int)HeroType.kNum)
            {
                LocationHooks.Log?.Warning(
                    $"[Evosanity] HeroStats index {i} is outside HeroType (kNum={(int)HeroType.kNum}) - " +
                    "the ball roster may have changed; re-run the [BALLDUMP] dump and regenerate game_data.json.");
                continue;
            }

            var ball = (HeroType)i;
            if (!EvosanityOptions.IsTracked(ball))
                continue;

            LocationHooks.SendCheck(EvosanityOptions.LocationNameFor(ball));
        }
    }

    /// <summary>
    /// True once every evolved ball has been discovered - half of the evosanity goal (the other
    /// half, all 8 biomes, stays with LocationHooks.ReportGoalIfComplete). Reads HeroStats
    /// directly rather than trusting _reported, so it's correct even before the poll has run.
    /// </summary>
    internal static bool AllEvolvedBallsDiscovered()
    {
        var stats = MetaSaveData.I?.HeroStats;
        if (stats == null)
            return false;

        foreach (var ball in GameNames.EvolvedBalls)
        {
            var idx = (int)ball;
            if (idx < 0 || idx >= stats.Length)
                return false;

            var s = stats[idx];
            if (s == null || s.NumObtained <= 0)
                return false;
        }

        return true;
    }

    /// <summary>How many evolved balls are discovered, for progress logging.</summary>
    internal static int EvolvedBallsDiscovered()
    {
        var stats = MetaSaveData.I?.HeroStats;
        if (stats == null)
            return 0;

        var count = 0;
        foreach (var ball in GameNames.EvolvedBalls)
        {
            var idx = (int)ball;
            if (idx < 0 || idx >= stats.Length)
                continue;

            var s = stats[idx];
            if (s != null && s.NumObtained > 0)
                count++;
        }

        return count;
    }
}
